name: model-training

on:
  pull_request:
    branches: [main]

permissions: write-all

jobs:
  train_and_report_eval_performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.16  # Match your project setup

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
          pip install dvc[s3]

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pull data with DVC
        run: |
          dvc pull

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Train model
        run: |
          poetry run python preprocess_dataset.py
          poetry run python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Model Evaluation Report" > model_eval_report.md
          cat metrics.json >> model_eval_report.md
          echo "![confusion matrix](./confusion_matrix.png)" >> model_eval_report.md

          cml comment create model_eval_report.md
