name: model-training

on:
  pull_request:
    branches: main

permissions: write-all

jobs:
  train_and_report_eval_performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.16'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Train model
        run: |
          poetry run python preprocess_dataset.py
          poetry run python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat metrics.json >> model_eval_report.md
          echo "![confusion matrix plot](./confusion_matrix.png)" >> model_eval_report.md
          poetry run cml comment create model_eval_report.md
